services:
  api:
    container_name: snappio-backend
    build: .
    command: poetry run daphne -b 0.0.0.0 backend.asgi:application
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    environment:
      # for production
      - RENDER=1
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis
  redis:
    image: redis:latest
